name: Deploy Azure Enterprise Scale Landing Zone
on:
  push:
      branches: [ main ]
  workflow_dispatch:


jobs:
  process-management-groups:
    uses: ./.github/workflows/1-process-management-groups.yml
    with: 
      az_powershell_min_version: ${{ vars.AZ_POWERSHELL_MIN_VERSION }}
    secrets: inherit