name: Challenge day 3 - energy prices
on:
  push:
      branches: '**'
  workflow_dispatch:

jobs:
  process-management-groups:
    uses: ./.github/workflows/challenge-1-deploy-keyvault.yml
    with: 
      az_powershell_min_version: ${{ vars.AZ_POWERSHELL_MIN_VERSION }}
    secrets: inherit

  